vim.keymap.set("v", "J", ":m '>+1<CR>gv=gv")
vim.keymap.set("v", "K", ":m '<-2<CR>gv=gv")
vim.keymap.set("x", "<leader>p", [["_dP]])
vim.keymap.set("n", "<leader>ff", "gg=G")
vim.keymap.set("n", "<leader>vs", "<Cmd>vsplit<CR>")
vim.keymap.set("n", "<leader>hs", "<Cmd>split<CR>")
vim.keymap.set("n", "<C-d>", "<C-d>zz")
vim.keymap.set("n", "<C-u>", "<C-u>zz")
vim.keymap.set("n", "n", "nzz")
vim.keymap.set("n", "N", "Nzz")


vim.keymap.set("n", "<leader>lg", "<Cmd>term lazygit<CR>")
vim.keymap.set("n", "<leader>he", "<Cmd>FzfLua helptags<CR>")
vim.keymap.set("n", "<leader><leader>", "<Cmd>FzfLua files<CR>")
vim.keymap.set("n", "<leader>ge", "<Cmd>FzfLua grep<CR>")
vim.keymap.set("n", "<leader>xx", "<Cmd>FzfLua diagnostics_workspace<CR>")
